### ISSUE TITLE
Can't compile on ubuntu 18.04

### ISSUE THREAD

**Issue by TomHarrop** [bcgsc/biobloom#34]
I'm having trouble compiling biobloom on ubuntu 18.04 with g++ 7.3.0.

Here's the output of make

```
make  all-recursive
make[1]: Entering directory '/biobloom'
Making all in Common
make[2]: Entering directory '/biobloom/Common'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/biobloom/Common'
Making all in BioBloomMaker
make[2]: Entering directory '/biobloom/BioBloomMaker'
g++ -DHAVE_CONFIG_H -I. -I..  -I/biobloom/BioBloomMaker -I/biobloom/Common -I/biobloom/DataLayer -I/biobloom -I/biobloom   -O3 -std=c++0x  -isystem/biobloom/1_58_0 -Wall -Wextra -Werror -fopenmp -g -O2 -MT biobloommaker-BioBloomMaker.o -MD -MP -MF .deps/biobloommaker-BioBloomMaker.Tpo -c -o biobloommaker-BioBloomMaker.o `test -f 'BioBloomMaker.cpp' || echo '/biobloom/BioBloomMaker/'`BioBloomMaker.cpp
In file included from BloomMapGenerator.h:18:0,
                 from BioBloomMaker.cpp:22:
../bloomfilter/MIBloomFilter.hpp:39:34: error: 'std::vector<std::vector<unsigned int> > parseSeedString(const std::vector<std::__cxx11::basic_string<char> >&)' defined but not used [-Werror=unused-function]
 static vector<vector<unsigned> > parseSeedString(
                                  ^~~~~~~~~~~~~~~
cc1plus: all warnings being treated as errors
Makefile:405: recipe for target 'biobloommaker-BioBloomMaker.o' failed
make[2]: *** [biobloommaker-BioBloomMaker.o] Error 1
make[2]: Leaving directory '/biobloom/BioBloomMaker'
Makefile:421: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/biobloom'
Makefile:341: recipe for target 'all' failed
make: *** [all] Error 2
```

Thanks!

**Comment by TomHarrop** [comment]
I got around it by install gcc-6 and g++-6, and using 
`./configure CXX=/usr/bin/g++-6 CC=/usr/bin/gcc-6`

**Comment by JustinChu** [comment]
Thanks for the report. I'll try to make sure this is resolved in the next release version.

**Comment by JustinChu** [comment]
Issue should be resolved in master branch (offending code should be removed)
